### ISSUE TITLE
Image disappears from media manager while re-uploading

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1198]
Image re-upload is neither confirmed nor canceled - image in media manager will disappear.

**Comment by Adomavicius** [comment]
I've traced the problem to be contained within [these lines](https://github.com/devbridge/BetterCMS/blob/c2b897a71c33a7314459789d4048cd1f916f9064/Modules/BetterCms.Module.MediaManager/Services/DefaultMediaImageService.cs#L202-L248). Due to the complex logic it may also be influenced by other pieces of code.

At the moment, when the user re-uploads an image, the property `IsTemporary` is set to true on the ORIGINAL image, instead of the new one. When the dialog is closed nothing changes in the database, therefore 'losing' the original image.

In order to fix this, the `IsTemporary` flag must be set on the NEW image and in case of dialog closure, the NEW image is the one that would be 'lost', allowing the old one to remain displayed.

As reference, the file uploading logic in the [DefaultMediaFileService](https://github.com/devbridge/BetterCMS/blob/c2b897a71c33a7314459789d4048cd1f916f9064/Modules/BetterCms.Module.MediaManager/Services/DefaultMediaFileService.cs) could be used, as the this particular bug does not exist with uploading files.

Another difference between the file and image uploading logic is that the `OriginalId` is set AFTER confirming the re-upload for files, but BEFORE confirming the re-upload for images.

**Comment by JuliusSenkus** [comment]
Made working version (have it in stash), but with bug related to better cms core modules so further discussion is needed.

**Comment by smikulenas** [comment]
Fix available from 1.10.1+
