### ISSUE TITLE
Need to add new font in the CkEditor Font dropdown

### ISSUE THREAD

**Issue by MrHarry01** [devbridge/BetterCMS#1278]
Hi,

We have some licensed version of fonts which we want to integrate in the font dropdown in the Editor.
Can you please help me out in this.

**Comment by Adomavicius** [comment]
In order to use additional fonts in the CKEditor you will need to make changes to and recompile the [BetterCms.Module.Root project](https://github.com/devbridge/BetterCMS/tree/dev/Modules/BetterCms.Module.Root).

The steps you need to take in order to add a new font to the CKEditor can be found in the following tutorial: https://www.outsystems.com/forums/discussion/13160/how-to-add-custom-fonts-on-ckeditor/

The location of the CKEditor scripts in the BetterCms solution is:
[Modules/BetterCms.Module.Root/Scripts/ckeditor/](https://github.com/devbridge/BetterCMS/tree/dev/Modules/BetterCms.Module.Root/Scripts/ckeditor)

Once you have made the necessary changes you will be required to reference the compiled root module dll in your project instead of the one downloaded by NuGet.

**Comment by MrHarry01** [comment]
Thanks Adomavicius....i will update you once i will integrate.
