### ISSUE TITLE
Update CKEditor for widgets

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1294]
- [x] Move smart region "Widget Option" to dedicated button
- [x] Add button to show rarely used tools
- [x] Increase height of text editor

**Comment by Audrunas** [comment]
Smart tags rendering in CSS / JS are implemented in #1328

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+

**Comment by daivabrazukaite** [comment]
1) Dropdowns  (smart tags, styles, format, font, size) values are not available on any browser except FF using Full view mode
2) Button for showing/hiding additional items (toolbar_collapser) title="undefined" 
3) Please double check when toolbar_collapser should be visible and what it is intended to do: to show/hide additional items or to show/hide additional toolbar row. Now some mix of these can be received using Full view mode as first click makes additional items visible, but later clicks shows/hides additional row(-s). Example: enter full view mode - initially main items are displayed. Click on toolbar_collapser: additional items in same row will appear, arrow will change. Click once more on it - nothing will happen as there are no additional rows to collapse, just arrow will change. Now make window width smaller, so that even main items do not fit into one row, and "play" with this button: after collapsing, only items fitting into one row will be displayed. If you decide that it is not worth to do anything, please add comment :)

**Comment by atamasauskas** [comment]
Fixed 2 and 3. @paulgabronis please take a look at 1, don't know why but dropdowns width is zero in full screen mode.

**Comment by smikulenas** [comment]
Fix available from 1.11.0-beta12+
