### ISSUE TITLE
Move out CSS & JavaScript to separate tab only for widgets

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1315]
- [x] Move to separate tab
- [x] Rename "Enable CSS editing" to "Render" and move to bottom
- [x] Rename "Enable JS editing" to "Render" and move to bottom
- [x] Implement automatic "Render" check box enabling on CSS or JS edit
- [x] Rename and move down "Enable HTML editing" check box
- [x] Increase height of text fields
- [x] Add tool bars for css & js text areas
- [x] Add Image, widget option and Smart Tags tools for css & js text areas

**Comment by paulgabronis** [comment]
There is no reason to keep this line with checkbox for html widgets, as it doesn't make any sense. Let's remove it, because if you want to use wiHTML widget it need to have some content otherwise it's not usable.
![screenshot at sep 23 17-29-32](https://cloud.githubusercontent.com/assets/2255639/10047853/bfc3c852-6218-11e5-9b0b-59d9263acb14.png)

**Comment by Audrunas** [comment]
- [ ] Implement automatic "Render" check box enabling on CSS or JS edit
> It's too complicated. As decided: by default, these checkboxes are checked

**Comment by Audrunas** [comment]
Fix will be available from 1.10.4-beta11+
