### ISSUE TITLE
Poor performance in Select Widget modal

### ISSUE THREAD

**Issue by KarolisBab** [devbridge/BetterCMS#1489]
To reproduce:
Go to any page > add widget

The result is captured in screenshot.

![select widget not performing](https://cloud.githubusercontent.com/assets/15941028/12234143/5cc5aca0-b873-11e5-9fb9-ebb62f44d647.PNG)

After a while:

![aww snap](https://cloud.githubusercontent.com/assets/15941028/12234029/06a701a2-b873-11e5-8222-d31d94085e67.PNG)

**Comment by smikulenas** [comment]
Update available from 2.0.0-preview2+

OK for IE & FF, but Chrome regarding memory management looks... not so good, but this can't be solved with current implementation with iFrames, because Chrome each iFrame loads in separate process, so there is a lot of overhead to show so many widgets at the same time.
