### ISSUE TITLE
Add multi language support

### ISSUE THREAD

**Issue by pauliusmaciulis** [devbridge/BetterCMS#842]
Whole site should be able to be translatable.
Ex: "Introduction" have a language dimension and a version dimension. (Every page is three dimensional). Only one version per language is available per publish and language is switched via icons or drop lists.

What's decided:
- Site settings -> create grid for managing languages
- When editing page - ability to assign page translations and change page language.
- API method for getting list of all languages by given page (pageUrls for redirecting to other cultures)
- cms.config value for disabling / enabling multilanguage support
- New button in sidebar - translate page: ability to create a new page from current page with different language
- In Site Settings update pages and blogs lists filters with ability to filter by language.

**Comment by Tim-bflow** [comment]
I am new to BCMS, but I was wondering about Multi-languages as this is always a requirement for me.  BCMS forces you to copy the whole page and translate it... what happens if you add new Content Sections/Regions to the original page?  Do those now show up in the other Lang pages so the content can be translated?

I think a better approach would be to allow to "Translating" each Content Section itself, so that if a particular Section was not translated, it would just fall back to a "default" Lang.

**Comment by smikulenas** [comment]
The idea, behind the translations per page vs. per section, was to allow pages to be able to be totally different in different languages, and sections would not give such flexibility.

**Comment by Tim-bflow** [comment]
Sure, that is understandable, but usually a site needs to maintain a consistent look-and-feel across multiple languages.  I have noticed that Widgets CAN be translated separately from the Page and maybe that's the approach I could take?

**Comment by smikulenas** [comment]
With widgets it's possible achieve desired functionality, but keep in mind, that in separate pages different widgets can be added.
